# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import wsil.models


class Migration(migrations.Migration):

    dependencies = [
        ('wsil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=30, null=True)),
                ('course_type', models.CharField(max_length=30, null=True)),
                ('logo', models.URLField(null=True)),
                ('photo_url', models.URLField(null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('workload', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('cache_date', models.DateTimeField(default=wsil.models.tomorrow, null=True)),
                ('source', models.CharField(default='COURSERA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(max_length=30, unique=True)),
                ('course_id', models.CharField(max_length=30, null=True)),
                ('partner_name', models.CharField(max_length=30, null=True)),
                ('partner_shortname', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_framework_name', models.CharField(max_length=40, unique=True)),
                ('ajax', models.CharField(max_length=30, null=True)),
                ('mvc_framework', models.CharField(max_length=40, null=True)),
                ('mvc_push_pull', models.CharField(max_length=40, null=True)),
                ('localization', models.CharField(max_length=40, null=True)),
                ('orm', models.CharField(max_length=40, null=True)),
                ('testing_framework', models.CharField(max_length=40, null=True)),
                ('db_migration_framework', models.CharField(max_length=40, null=True)),
                ('security_framework', models.CharField(max_length=40, null=True)),
                ('template_framework', models.CharField(max_length=40, null=True)),
                ('caching_framework', models.CharField(max_length=40, null=True)),
                ('form_validation_framework', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestByRegionFrameworkLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_or_lib', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30, null=True)),
                ('interest_rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestByRegionLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30, null=True)),
                ('interest_rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestOverTimeFrameworkLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_or_lib', models.CharField(max_length=30)),
                ('date', models.DateTimeField(null=True)),
                ('interest_rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestOverTimeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(null=True)),
                ('interest_rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150, null=True)),
                ('post_date', models.CharField(max_length=10, null=True)),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('company_url', models.URLField(null=True)),
                ('location_name', models.CharField(max_length=30, null=True)),
                ('lang', models.CharField(max_length=3, null=True)),
                ('query', models.CharField(max_length=30, null=True)),
                ('cache_date', models.DateTimeField(default=wsil.models.tomorrow, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryOrFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('initial_release', models.CharField(max_length=100, null=True)),
                ('stable_release', models.CharField(max_length=100, null=True)),
                ('release_date', models.CharField(max_length=50, null=True)),
                ('repository', models.URLField(null=True)),
                ('development_status', models.CharField(max_length=10, null=True)),
                ('license', models.CharField(max_length=10, null=True)),
                ('website', models.URLField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('language', models.ManyToManyField(null=True, to='wsil.Language')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOnIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
                ('count', models.IntegerField()),
                ('cache_date', models.DateTimeField(default=wsil.models.tomorrow, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interestovertimelanguage',
            unique_together=set([('language_name', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='interestovertimeframeworklibrary',
            unique_together=set([('fw_or_lib', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='interestbyregionlanguage',
            unique_together=set([('language', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='interestbyregionframeworklibrary',
            unique_together=set([('fw_or_lib', 'region')]),
        ),
    ]
